version: "3.7"

services:

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx.conf/nginx.proxy.conf:/etc/nginx/conf.d/z-overrides.conf
    ports:
      - 80:80

  site2:
    image: nginx:alpine
    container_name: site2
    volumes:
      - ./nginx.conf/nginx.site2.conf:/etc/nginx/conf.d/z-overrides.conf

  site3:
    image: nginx:alpine
    container_name: site3
    volumes:
      - ./nginx.conf/nginx.site3.conf:/etc/nginx/conf.d/z-overrides.conf

  site1-loadbalance1:
    image: nginx:alpine
    container_name: site1-loadbalance1
    volumes:
      - ./nginx.conf/nginx.site1.loadbalance1.conf:/etc/nginx/conf.d/z-overrides.conf

  site1-loadbalance2:
    image: nginx:alpine
    container_name: site1-loadbalance2
    volumes:
      - ./nginx.conf/nginx.site1.loadbalance2.conf:/etc/nginx/conf.d/z-overrides.conf

  site1-loadbalance3:
    image: nginx:alpine
    container_name: site1-loadbalance3
    volumes:
      - ./nginx.conf/nginx.site1.loadbalance3.conf:/etc/nginx/conf.d/z-overrides.conf