version: "3.7"

services:

  webserver:
    image: nginx:alpine
    depends_on:
      - php-fpm
    container_name: webserver
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/zzz99-overrides.conf
      - ./ssl/:/etc/ssl
    ports:
      - 80:80
      - 443:443

  php-fpm:
    image: devilbox/php-fpm:7.4-prod
    container_name: phpfpm
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html/
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz99-overrides.conf
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zzz99-overrides.ini
    ports:
      - 9000:9000